remote_theme: olindsa2024/minimal-mistakes@copybutton
logo: "https://qeacourse.github.io/RoboNinjaWarrior/website_graphics/olinlogo.png"
title: "Data Structures Spring 2024 @ Olin College"
repository: olindsa2024/olindsa2024.github.io
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: true
